### ISSUE TITLE
Got segment fault after patching

### ISSUE THREAD

**Issue by sinkthemall** [robbert1978/alt-pwninit#5]
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/2c8d67e8-362f-4eeb-adc7-b4720f97f8d4)
after I patched with alt-pwninit, when I tried to run the file, this happened

**Comment by robbert1978** [comment]
Can you try to run `ldd ./..._patched` and show me the result ?

**Comment by sinkthemall** [comment]
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/d8522db0-c0b9-4ef0-83e9-32ef969d74ce)
yes, here it is

**Comment by robbert1978** [comment]
I see, some how it couldn't create `libc.so.6` symlink to your libc file. There is a log file `/tmp/pwninit_log`, can you show me the content of this file ?

**Comment by sinkthemall** [comment]
![image](https://github.com/robbert1978/alt-pwninit/assets/92171234/8ef0dd8f-7e0b-4e47-8479-4b298c69445a)
It seem likes nothing is written to it

**Comment by robbert1978** [comment]
Oh I know the problem now, copy `../libc-2.27.so` to `.`(current dir) . I think that should work.

**Comment by robbert1978** [comment]
Or you can make the symlink `./libc-2.27.so` to `../libc-2.27.so`.

**Comment by sinkthemall** [comment]
should I try to move the libc to current folder?

**Comment by sinkthemall** [comment]
ah yes it work, ty
