### ISSUE TITLE
Unable to extract libc version

### ISSUE THREAD

**Issue by sinkthemall** [robbert1978/alt-pwninit#6]
![image](https://github.com/user-attachments/assets/1728141e-bd1d-43ed-baa2-889e5b48b032)
There is some error when extracting libc version, the libc version I'm using is "GNU C Library (Debian GLIBC 2.36-9+deb12u9) stable release version 2.36."

**Comment by robbert1978** [comment]
Bro, please read `readme.md`
![image](https://github.com/user-attachments/assets/f2ba394f-a589-416c-99ef-a4bbf3df1be0)

**Comment by robbert1978** [comment]
You can manually download the debug symbols from [here](http://ftp.cn.debian.org/debian/pool/main/g/glibc/libc6-dbg_2.36-9+deb12u9_amd64.deb). 

The process for unstripping Debian's libc is different from that of Ubuntu. Honestly, I'm too lazy to write a new script for it, but feel free to contribute to this project if you'd like.

Let me know if you need further support.
